---
  title: "Experiences"
  output:
   html_document:
     toc: true
     toc_float: true
     collapsed: false
     number_sections: FALSE
     toc_depth: 3
     #code_folding: hide
     smooth_scroll: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

### Education

#### Ph.D. Student
* University of Bath, Sep 2024-present
* Area of research: [Co-occurrence of antisocial behaviour and substance use from adolescence to early adulthood](https://researchportal.bath.ac.uk/en/projects/co-occurrence-of-antisocial-behaviour-and-substance-use-from-adol) (funded by the ESRC SWDTP, Advanced Quantitative Methods interdisciplinary pathway)
* Supervisor(s): [Dr Jennifer Allen](https://researchportal.bath.ac.uk/en/persons/jennifer-allen) and [Dr Tom Freeman](https://researchportal.bath.ac.uk/en/persons/tom-freeman) and Dr Gemma Hammerton (University of Bristol) 

#### Master of Education
* Guangzhou University, 2016 Sep-2020 Jun
* Specialization: Applied Psychology
* Master thesis: Developmental trajectories of callous-unemotional traits: Longitudinal associations with parenting stress and parenting behaviours in Chinese community children
* Supervisor: Dr Mengcheng Wang 

#### Bachelor of Science
* Guangzhou University, 2012 Sep-2016 Jun
* Specialization: Psychology
* Bachelor thesis: The relationship between psychopathy and the five-factor model
* Supervisor: Dr Mengcheng Wang

### Honors and Academic Awards
* Economic and Social Research Council (ESRC)-funded studentship (Mar 2024)
* Outstanding student of Guangdong Province in 2020 (Apr 2020)
* Outstanding graduates of Guangzhou University in 2020 (May 2020)
* The National Scholarship in 2019 (Nov 2019)
* Scholarship for abroad as a joint graduate student (Jun 2018)
* Second prize scholarship of School of Education at Guangzhou University (Oct 2018)
* The National Scholarship in 2017 (Nov 2017)
* First prize scholarship of School of Education at Guangzhou University (Oct 2017)
* Second prize scholarship of School of Education at Guangzhou University (Oct 2016)
* Second prize of essay activity of Psychology Sub-forum of Graduate Academic Forum of Guangzhou University (Dec 2016)

### Research Experience
#### Research fellow, Jul 2022-Jul 2024 
* The Centre for Psychometric and Latent Variable modeling, Guangzhou University, Guangzhou, China
* Principle Investigator: Dr Mengcheng Wang  
* Main Contributed Projects
  + Developing risk assessment tools using ML in offenders
  + Online assessments platform management

#### Visiting student, Dec 2018-Dec 2019
* Psychophysiology Lab at Brooklyn College, CUNY, New York, NY, USA.  
* Principle Investigator: Dr Yu Gao  

#### Research assistant, May 2015-Apr 2021
* The Centre for Psychometric and Latent Variable Modeling, Guangzhou University, Guangzhou, China
* Principle Investigator: Dr Mengcheng Wang
* Responsibilities: Data collection and analysis, Manuscript and research report writing.
* Main Contributed Projects
  + Risk assessment in psychiatric prisoners, Guangdong, China.
  + A longitudinal study in schoolchildren using multi-informant approach, Guangdong, China.
  + Developing measure for burden and physical-mental facets in youth, Chongqing, China.

### Conferences and Presentations
1.	**Deng, J.**, Wang, M., Shou, Y., Gao, Y., Allen, J. & Hawes, D. (Apr 2023). Cross-cultural Network Analysis of Callous-Unemotional Traits in Four International Youth Samples. Oral presentation at the meeting of Guangzhou Psychological Association. Guangzhou University, Guangzhou, China.
2.	**Deng, J.**, Wang, M., Gao, Y. & Shou, Y. (May 2019). Parenting Behaviors and Child Psychopathy: A Regression Mixture Analysis. Poster presented at the 8th biennial meeting of the Society for the Scientific Study of Psychopathy. Las Vegas, USA. 
3.	**Deng, J.**, Zhang, X., Gao, Y., Wang, M. & Shou, Y. (Nov 2017). The Utility of Limited Prosocial Emotion: Meta-analysis and reliability generalization of the Inventory of Callous Unemotional Traits. Oral presentation at Guangzhou-Hong Kong Graduate Forum 2017. Guangzhou University, Guangzhou, China.
4.	**Deng, J.**, Zhang, X., Gao, Y., Wang, M. & Shou, Y. (Nov 2017). The Utility of Limited Prosocial Emotion: Meta-analysis and reliability generalization of the Inventory of Callous Unemotional Traits. Oral presentation at the 20th National Psychology Conference. Southwest University, Chongqing, China.
5.	**Deng, J.** & Wang, M. (Jul 2017). The relations between psychopathy and the Five-Factor Model. Oral presentation at International Postgraduate Roundtable and Research Forum cum Summer School 2017. The Education University of Hong Kong, Hong Kong, China.

### Workshops Presentations
1.	**Deng, J.** (2023). Meta-analysis and Reliability Generalization Workshop. 22 Mar, Guangdong University of Technology, Guangzhou, China.
2.	**Deng, J.** (2023). Network psychometrics Workshop. 9 Mar, Virtual.
3.	Wang, M-C., **Deng, J.** (2022). Network psychometrics Workshop. 19 June, Virtual.
4.	Wang, M-C., **Deng, J.** (2022). Reliability Generalization Workshop. 16 July, Changsha, China.

### Work Experience
#### Data Analyst in Educational Assessment, Apr 2021-June 2022
* Jingwei Reading Technology Co., Ltd, Beijing, China
* Analyzing data and interpreting results using statistics techniques especially psychometric testing

#### Psychology teacher (Internship), Sep 2015-Dec 2015
* Guangzhou Tianhe Middle School, Guangzhou, China
* Supervisor: Yang Yang, B.S. (Psychology teacher)

#### Social worker (Internship), May 2015-Aug 2015
* Guangzhou QiChuang Social Work Service Centre, Guangzhou, China.
* Supporting services for social reintegration for drug users, preventive education & anti-drug publicity
* Supervisor: Wang Jing, B.S. (Senior social worker)

### Qualifications and Skills
#### Statistical and programming skills
  + R programming (as primary tools for analysis), Mplus, SPSS, E-prime, SQL (Basic)
  + Data cleaning and wrangling, data visualisation. 
  + Structural Equation Modelling
  + Psychometrics (e.g., Item analysis, Factor Analysis)
  + Network Analysis in R (e.g., qgraph, bootnet, NetworkComparisonTest)
  + Meta-Analysis (e.g., reliability generalization using metafor)
  + Machine Learning and prediction (e.g., Random Forests, Neural Network, ROC curve).

#### Language Acquisition
  + English/Mandarin/Cantonese

