---
title: "Publications"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#### Network analysis
Wang, M-C. & **Deng, J.** (2023). Reliability Generalization. In Wang, M-C. & Liu, T (Eds.), *Quantitative Research Method in Psychological and Behavioural Science*(in Chinese) (pp. 171-176). Chongqing University Press.  
Wang, M-C. & **Deng, J.** (2023). Network analysis. In Wang, M-C. & Liu, T (Eds.), *Quantitative Research Method in Psychological and Behavioural Science*(in Chinese) (pp. 198-208). Chongqing University Press.  
Li, J., **Deng, J.**, Xu, J. (2023). Which Well-Being Elements Are Fundamental for Early Childhood Educators in the Chinese Context? A Network Analysis. *Journal of School Psychology*. Manuscript submitted for publication    
Liu, H., **Deng, J.**, He, J., Zhao, L., Zhang, X. & Wang, M-C. (2023). A Network Analysis of Depression and Anxiety and Their Associations with Resilience and Self-Esteem During the Late Stage of the COVID-19 Pandemic in China. *Journal of Affective Disorders*. Manuscript submitted for publication    
Zhang, X., **Deng, J.**, Shou, Y., & Wang, M. C. (2022). Longitudinal network structure of child psychopathy across development in chinese community children. *Current Psychology*. https://doi.org/10.1007/s12144-022-03799-0  
Wang, M.-C., **Deng, J.**, Shou, Y., & Sellbom, M. (2022). Cross-cultural examination of psychopathy network in Chinese and U.S. Prisoners. *Journal of Psychopathology and Behavioral Assessment*. Advance online publication. https://doi.org/10.1007/s10862-022-09960-0  
**Deng, J.**, Wang, M-C., Shou, Y., & Gao, Y. (2020). Core features of Callous-Unemotional Traits: Network analysis of the Inventory of Callous-Unemotional Traits in community and offender Samples. *Journal of Clinical Psychology*.*77*, 1487–1498. https://doi.org/10.1002/jclp.23090  

#### Meta-analysis
Wang, M-C., **Deng, J.**, Zhang, X., Liang, J., & Shou, Y. (2023). A Reliability Generalization Meta-Analysis of the Antisocial Process Screening Device. *Assessment*. Manuscript submitted for publication  
Liang, J., Shou, Y., Wang, M-C., **Deng, J.**, & Luo, J. (2021). A reliability generalization meta-analysis of Alabama Parenting Questionnaire-9. *Psychological Assessment*. *33*, 940–951. https://doi.org/10.1037/pas0001031  
**Deng, J.**, Wang, M.-C., Zhang, X., Shou, Y., Gao, Y., & Luo, J. (2019). The Inventory of Callous Unemotional Traits: A reliability generalization meta-analysis. *Psychological Assessment*, *31*, 765–780. http://dx.doi.org/10.1037/pas0000698.  

#### Latent variables modeling
Wang, M.-C., Zhang, X., Gong, J., **Deng, J.**, Luo, J., Gao, Y., & Salekin, R. T. (2022). Variants of Psychopathy in Chinese Juvenile Offenders: A Latent Profile Analysis. *Criminal Justice and Behavior*, *49*, 530–549. https://doi.org/10.1177/00938548211043149   
**Deng, J.**, Wang, M., Shou, Y., Lai, H., Zeng, H., & Gao, Y. (2020). Parenting Behaviors and Child Psychopathy: A Regression Mixture Analysis. *Current Psychology*.*41*, 3585–3596. https://doi.org/10.1007/s12144-020-00810-4  
Zhong, C., Wang, M-C., Shou, Y., Zhang, X., & **Deng, J.** (2020). Maternal Parenting Mediate the Relationship between Maternal Psychopathic Traits and 8 to 11-year-old Child Callous-Unemotional Traits: A Longitudinal Multiple Mediation Model. *Journal of Child and Family Studies*, *29*, 3142–3152. https://doi.org/10.1007/s10826-020-01814-1  


#### Psychometries
Luo, J., Wang, M.-C., Gao, Y., **Deng, J.**, & Qi, S.-S. (2020). Factor structure and construct validity of the Emotions as a Child Scale (EAC) in Chinese children. *Psychological Assessment*, *32*, 85–97. https://doi.org/10.1037/pas0000762.  
Luo, J., Wang, M. C., Zhang, X., **Deng, J.**, Huang, D., & Zhou, Z. (2020). Psychometric Properties of the Youth Psychopathic Traits Inventory Triarchic Scales and Its Short Version in Chinese Male Juvenile Offenders. *Journal of Personality Assessment*, 1–12. Advance online publication. https://doi.org/10.1080/00223891.2020.1752700  
Wang, M.-C., Deng, Q., Shou, Y., Lai, H., **Deng, J.**, Gao, Y., & Li, Z. (2019). Assessing Impulsivity in Chinese: Elaborating Validity of BIS Among Male Prisoners. *Criminal Justice and Behavior*, *46*, 492–506. https://doi.org/10.1177/0093854818806033  
Zhang, X., Wang, M-C., He, L., L, J., **Deng, J.** (2019). The development and psychometric evaluation of the Chinese Big Five Personality Inventory-15. *PLoS ONE*, *14*, e0221621. https:// doi.org/10.1371/journal.pone.0221621  
Ren, F., Zhang, Q., Li, M., Luo, J., **Deng, J.**, Zhang, X., & Wang, M-C. (2019). The Factor structure and Construct validity of the Youth Psychopathic Traits Inventory child version. *Frontiers in Psychology*, *10*, 2550. doi: 10.3389/fpsyg.2019.02550  
Luo, J., Wang, X., Wang, M-C, Wang, X., Gao, Y., **Deng, J.**, Zhong, C., & Qi, S-S. (2019). Longitudinal measurement invariance of the Child Problematic Trait Inventory in older Chinese children. *PLoS ONE*, *14*, e0219136. https://doi.org/10.1371/journal.pone.0219136    
Wang, M.-C., Colins, O. F., Deng, Q., **Deng, J.**, Huang, Y., & Andershed, H. (2018). The Child Problematic Traits Inventory in China: A multiple informant-based validation study. *Psychological Assessment*, *30*, 956–966. http://dx.doi.org/10.1037/pas0000545.  
Wang, M-C., Gao, Y., **Deng, J.**, Lai, H., Deng, Q., & Armour, C. (2017). The factor structure and construct validity of the inventory of callous-unemotional traits in Chinese undergraduate students. *PLoS ONE*, *12*, e0189003. https://doi.org/10.1371/journal.pone.0189003.  
Wang, M-C., Colins, O. F., Deng, Q., Andershed, H, **Deng, J.**, & Ye, H. (2017). Psychometric properties of the original and short version of the Youth Psychopathic Traits Inventory among Chinese adolescents. *Journal of Psychopathology and Behavioral Assessment*, *39*, 620–634.  

##### In Chinese
(Chinese Journal of Clinical Psychology was rated as one of the most influential Chinese journals especially in clinical psychology and asessment.)  

Wang, J., **Deng, J.**, Lai, H., Wang, M-C. (2019). Sex difference in processing negative emotion in adolescents with different level of callous unemotional trait. *Chinese Mental Health Journal*, *33*, 109–113.  
**Deng, J.**, Zhao, Ying., Wang, Rong., Wang, M-C. (2019). The relationship between psychopathy and the five-factor model. *Journal of Guizhou Normal University (Natural Sciences)*, *37*, 114–120.  
Xu, W., Wang, M-C., **Deng, J.**, Liu, H., Yang, W. (2019). A reliability generalization meta-analysis for the Chinese version of Strengths and Difficulties Questionnaire. *Chinese Journal of Clinical Psychology*, *27*, 67–72  
**Deng, J.**, Yang, R., Wang, M-C., Deng, Q., & Liu, J. (2017). Psychometric Properties of Narcissistic Admiration and Rivalry Questionnaire in Chinese Adolescent. *Chinese Journal of Clinical Psychology*, *25*, 445–447.  
Deng, Q., **Deng, J.**, Huang, Y., & Wang, M-C. (2017). The Factor Structure and Psychometric Properties of the Levenson Self-Report Psychopathic Scale. Chinese Journal of Clinical Psychology, 25, 659–661.  
Deng, Q., Ding, C., Liu, M., **Deng, J.** & Wang, M-C. (2016). Psychometric Properties of the Inventory of Callous-Unemotional in Preschool Students. *Chinese Journal of Clinical Psychology*, *24*, 663–666. doi: 10.16128/j.cnki.1005-3611.2016.04.020  
Liu, M., Cheng, J., Deng Q., Huang, Y, **Deng, J.**, Zeng, H., & Wang, M-C. (2016). The preliminary assessment of the Antisocial Process Screening Device-Self-Report in adolescents. *Chinese Journal of Clinical Psychology*, *24*, 1016–1020. doi: 10.16128/j.cnki.1005-3611.2016.06.012  
