<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Jiaxin Deng" />


<title>Reliability Generalization Workshop</title>

<script src="site_libs/header-attrs-2.21/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/cerulean.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/font-awesome-6.4.0/css/all.min.css" rel="stylesheet" />
<link href="site_libs/font-awesome-6.4.0/css/v4-shims.min.css" rel="stylesheet" />

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Jiaxin Deng</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Home</a>
</li>
<li>
  <a href="Cv.html">Curriculum Vitae</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Publications
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="publications_year.html">Sort by Year</a>
    </li>
    <li>
      <a href="publications_topic.html">Sort by Topic</a>
    </li>
  </ul>
</li>
<li>
  <a href="Experiences.html">Experiences</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Tutorials
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="Tutorial_Reliability-Generalization.html">Reliability Generalization</a>
    </li>
    <li>
      <a href="Tutorial_Network-analysis.html">Network Analysis</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://github.com/KammyDeng">
    <span class="fa fa-github"></span>
     
  </a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Reliability Generalization Workshop</h1>
<h4 class="author">Jiaxin Deng</h4>
<h4 class="date">2022/7/16</h4>

</div>


<p>———-Table of Contents——————————————————————————————–<br />
———- 1. Meta-analysis in R ————————————————————–<br />
———- 2. Example: Deng et al. (2019) Reliability generalization of the
ICU———————–<br />
———- Hands-on exercises: Practice with demo
data——————————————————-<br />
———- 3. Summary——————————————————————————————<br />
———- 4. Resources ——————————————————————————–</p>
<div id="meta-analysis-in-r" class="section level2">
<h2>1. Meta-analysis in R</h2>
<p><em>R</em> programming is commonly used in the data analysis of
meta-analysis and reliability generalization.</p>
<p>Several commonly used R packages in the meta-analysis include
<code>metafor</code>(Viechtbauer, 2010), <code>metaSEM</code> (Cheung,
2015), etc. For details, see Polanin et al. (2017). This review
summarizes 63 currently available packages for meta-analysis and
provides comparisons and suggestions for their use in terms of
functions.</p>
<p>Polanin, J. R., Hennessy, E. A., &amp; Tanner-Smith, E. E. (2017). A
Review of Meta-Analysis Packages in R. <em>Journal of Educational and
Behavioral Statistics</em>, <em>42</em>, 206–242.</p>
<p>One of the most widely used packages for conducting meta-analysis is
<code>metafor</code>, which was written and developed by Professor
Wolfgang Viechtbauer of Maastricht University in the Netherlands.
Compared with other packages, <code>metafor</code> covers the
statistical analysis process of meta-analysis quite comprehensively,
including calculating effect size, conducting moderator analysis,
analyzing publication bias, and using multi-level models to deal with
nested dependent variable effect size.</p>
<p>Many RG studies used the<code>metafor</code>package as a tool for
statistical analysis, such as:</p>
<p>[1] Blázquez-Rincón, D., Durán, J. I., &amp; Botella, J. (2022). The
fear of COVID-19 scale: a reliability generalization meta-analysis.
<em>Assessment</em>, <em>29</em>, 940–948.</p>
<p>[2] Rubio-Aparicio, M., Núñez-Núñez, R. M., Sánchez-Meca, J.,
López-Pina, J. A., Marín-Martínez, F., &amp; López-López, J. A. (2020).
The Padua Inventory–Washington State University Revision of obsessions
and compulsions: A reliability generalization meta-analysis. <em>Journal
of Personality Assessment</em>, <em>102</em>, 113–123.</p>
<p>[3] Vicent, M., Rubio-Aparicio, M., Sánchez-Meca, J., &amp;
Gonzálvez, C. (2019). A reliability generalization meta-analysis of the
child and adolescent perfectionism scale. <em>Journal of Affective
Disorders</em>, <em>245</em>, 533–544.</p>
<p>[4] Piqueras, J. A., Martín-Vivar, M., Sandin, B., San Luis, C.,
&amp; Pineda, D. (2017). The Revised Child Anxiety and Depression Scale:
A systematic review and reliability generalization meta-analysis.
<em>Journal of affective disorders</em>, <em>218</em>, 153–169.</p>
<p>[5] López-Pina, J. A., Sánchez-Meca, J., López-López, J. A.,
Marín-Martínez, F., Núñez-Núñez, R. M., Rosa-Alcázar, A. I., … &amp;
Ferrer-Requena, J. (2015). The Yale–Brown obsessive compulsive scale: A
reliability generalization meta-analysis. <em>Assessment</em>,
<em>22</em>, 619–628.</p>
<p>Therefore, the following example studies will demonstrate how to
perform statistical analysis using the <code>metafor</code> package
(Viechtbauer, 2010).</p>
<p>##2. Example: Deng et al. (2019) Reliability generalization of the
ICU</p>
<div id="brief-introduction" class="section level3">
<h3>Brief introduction</h3>
<p>The following is an RG example of the Inventory of
Callous-Unemotional traits (Deng et al., 2019), specifically describe
how to conduct an RG study, focusing on software operations for
statistical analysis.</p>
<p>The 24-item scale contains three subscales, Callousness, Uncaring,
and Unemotional, using Likert 4 scored. Here is a brief summary of the
specific process:</p>
<div id="preparation" class="section level4">
<h4>Preparation</h4>
<div id="literature-search-and-screening" class="section level5">
<h5>1. Literature search and screening</h5>
<p>In this study, a total of 1,125 articles were downloaded from
multiple databases using multiple keywords. After applying filtering
criteria, 146 articles were ultimately retained.</p>
</div>
<div id="data-extraction-and-encoding" class="section level5">
<h5>2. Data extraction and encoding</h5>
<ol style="list-style-type: decimal">
<li>Effect size: the total score and its subscale Cronbach’s alpha
coefficient<br />
</li>
<li>The moderators are included as follows:<br />
</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>SD of age<br />
</li>
<li>Mean age<br />
</li>
<li>% of males in sample<br />
</li>
<li>sample size<br />
</li>
<li>SD of total scores<br />
</li>
<li>Mean of total scores<br />
</li>
<li>administration format<br />
</li>
<li>age group<br />
</li>
<li>sample type<br />
</li>
<li>language version<br />
</li>
<li>country<br />
</li>
<li>item number version</li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Data analysis In this section, the total score α coefficient of the
scale (24 items) and the moderators of 53 studies in this study were
selected as demo data.<br />
</li>
</ol>
<ul>
<li>effect size: the alpha coefficient of the total score of the
scale<br />
</li>
<li>Continuous variables: sample size, mean age and standard deviation,
gender percentage, mean and standard deviation of the total score<br />
</li>
<li>Categorical variables: age type, sample type, language,
adminstration ratings</li>
</ul>
<p>Examples of specific encoding rules are as follows:</p>
<pre class="r"><code>criteria %&gt;% knitr::kable()</code></pre>
<table>
<colgroup>
<col width="17%" />
<col width="35%" />
<col width="18%" />
<col width="19%" />
<col width="9%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="left">c1</th>
<th align="left">c2</th>
<th align="left">c3</th>
<th align="left">c4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">agetype</td>
<td align="left">Infants and young children</td>
<td align="left">Children</td>
<td align="left">Adolescents</td>
<td align="left">Adults</td>
</tr>
<tr class="even">
<td align="left">sampletype</td>
<td align="left">community</td>
<td align="left">offender</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="odd">
<td align="left">language</td>
<td align="left">english</td>
<td align="left">non-english</td>
<td align="left">NA</td>
<td align="left">NA</td>
</tr>
<tr class="even">
<td align="left">ratingformat</td>
<td align="left">self-report</td>
<td align="left">parent-report</td>
<td align="left">teacher-report</td>
<td align="left">NA</td>
</tr>
</tbody>
</table>
<p>Next, I will demonstrate how to conduct the analysis using demo
data.</p>
</div>
</div>
</div>
<div id="installation-and-load-packages" class="section level3">
<h3>2.1.1 Installation and load packages</h3>
<p>First, install and run the package. The code is displayed as
follows:</p>
<pre class="r"><code>library(readxl)
library(openxlsx) 
options(tidyverse.quiet = TRUE)
library (tidyverse) 
library(metafor)</code></pre>
</div>
<div id="data-reading-and-import" class="section level3">
<h3>2.1.2 Data reading and import</h3>
<p>To use the example shown, you first need to import the data. Since
the data file is in Excel format, you can use the <code>readxl</code>
package to read and import the data. Use this code with the appropriate
file path to import the data.</p>
<pre class="r"><code>data&lt;-read_excel(&quot;example_data.xlsx&quot;) #demo data in the current working directory
head(data,10)#10 rows</code></pre>
<pre><code>## # A tibble: 10 × 13
##    `study ID` agetype sampletype language ratingformat  ageM ageSD gender  size
##         &lt;dbl&gt;   &lt;dbl&gt;      &lt;dbl&gt;    &lt;dbl&gt;        &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt; &lt;dbl&gt;
##  1          1       3          1        1            1  15.0  1.3   0        58
##  2          2       3          2        2            1  16.7  1.34  0.56    352
##  3          3       3          1        1            1  15.9  1.53  1       150
##  4          4       3          1        1            1  15.2  1.4   0.6     150
##  5          5       4          2        1            1  19.9  3.48  0.3     602
##  6          6       3          2        1            1  16.9  0.8   0.48    675
##  7          7       3          2        2            1  16    0.89  0.503  2306
##  8          8       2          2        2            1  10    1.19  1        46
##  9          9       4          2        1            1  21.3  4.65  0.224   687
## 10         10       3          1        1            1  15.3  1.34  0.716   134
## # ℹ 4 more variables: totalSD &lt;dbl&gt;, totalM &lt;dbl&gt;, alpha_total &lt;dbl&gt;, mi &lt;dbl&gt;</code></pre>
<pre class="r"><code>#data consists of 3 parts:
#(1) Effect size: alpha
#(2) Continuous regulation variables
#(3) Categorical moderators

#read_excel(&quot;path/to/data_file.xlsx&quot;) #specific path</code></pre>
</div>
<div id="heterogeneity-testing" class="section level3">
<h3>2.2 Heterogeneity testing</h3>
<p>To examine heterogeneity in the effect size, the variability of the α
coefficients was mainly tested using the <code>rma()</code>
function.</p>
<p>Before testing for heterogeneity, the effect size needs to be
calculated, which is done mainly by the <code>escalc()</code>
function.</p>
<p>The <code>escalc()</code> function include the following
parameters:<br />
(1) measure is used to convert Cronbach’s α coefficient or use the
original value;<br />
(2) ai is the observed Cronbach’s α coefficient;<br />
(3) ni is the sample size and mi is the number of items;<br />
(4) dat is the dataset.</p>
<p>For example, to use the form without transformation, set measure to
“ARAW” with the following code:</p>
<pre class="r"><code>#raw alpha
total_es_raw&lt;-escalc(measure = &quot;ARAW&quot;, ai=alpha_total, ni=size, mi=mi, dat=data)
total_es_raw[1:10,]#yi--effect size,vi--sampling variance; the first 10 rows</code></pre>
<pre><code>## 
##    study.ID agetype sampletype language ratingformat  ageM   ageSD gender size 
## 1         1       3          1        1            1 14.98 1.30000  0.000   58 
## 2         2       3          2        2            1 16.67 1.34000  0.560  352 
## 3         3       3          1        1            1 15.89 1.53000  1.000  150 
## 4         4       3          1        1            1 15.20 1.40000  0.600  150 
## 5         5       4          2        1            1 19.90 3.48000  0.300  602 
## 6         6       3          2        1            1 16.90 0.80000  0.480  675 
## 7         7       3          2        2            1 16.00 0.89000  0.503 2306 
## 8         8       2          2        2            1 10.00 1.18875  1.000   46 
## 9         9       4          2        1            1 21.30 4.65000  0.224  687 
## 10       10       3          1        1            1 15.34 1.34000  0.716  134 
##    totalSD totalM alpha_total mi     yi     vi 
## 1     9.17  23.50        0.79 24 0.7900 0.0016 
## 2     9.17  24.05        0.83 24 0.8300 0.0002 
## 3     7.41  28.70        0.64 24 0.6400 0.0018 
## 4     6.04  46.50        0.84 24 0.8400 0.0004 
## 5     7.53  41.79        0.80 24 0.8000 0.0001 
## 6     7.85  21.62        0.79 24 0.7900 0.0001 
## 7     8.72  23.65        0.80 24 0.8000 0.0000 
## 8     7.23  20.30        0.73 24 0.7300 0.0035 
## 9     6.75  37.44        0.81 24 0.8100 0.0001 
## 10   10.11  41.64        0.85 24 0.8500 0.0004</code></pre>
<p>If use the Bonett (2002) formula for conversion, set measure to “ABT”
with the following code:</p>
<pre class="r"><code>#use Bonett&#39;s (2002) formula to convert and calculate the weighted average alpha coefficient
total_es &lt;- escalc(&quot;ABT&quot;,-ln(1-ai), ai=alpha_total, ni=size, mi=mi, dat=data)
total_es[1:10,] #yi--effect size, vi--sampling variance; Look at the first 10 rows</code></pre>
<pre><code>## 
##    study.ID agetype sampletype language ratingformat  ageM   ageSD gender size 
## 1         1       3          1        1            1 14.98 1.30000  0.000   58 
## 2         2       3          2        2            1 16.67 1.34000  0.560  352 
## 3         3       3          1        1            1 15.89 1.53000  1.000  150 
## 4         4       3          1        1            1 15.20 1.40000  0.600  150 
## 5         5       4          2        1            1 19.90 3.48000  0.300  602 
## 6         6       3          2        1            1 16.90 0.80000  0.480  675 
## 7         7       3          2        2            1 16.00 0.89000  0.503 2306 
## 8         8       2          2        2            1 10.00 1.18875  1.000   46 
## 9         9       4          2        1            1 21.30 4.65000  0.224  687 
## 10       10       3          1        1            1 15.34 1.34000  0.716  134 
##    totalSD totalM alpha_total mi     yi     vi 
## 1     9.17  23.50        0.79 24 1.5606 0.0373 
## 2     9.17  24.05        0.83 24 1.7720 0.0060 
## 3     7.41  28.70        0.64 24 1.0217 0.0141 
## 4     6.04  46.50        0.84 24 1.8326 0.0141 
## 5     7.53  41.79        0.80 24 1.6094 0.0035 
## 6     7.85  21.62        0.79 24 1.5606 0.0031 
## 7     8.72  23.65        0.80 24 1.6094 0.0009 
## 8     7.23  20.30        0.73 24 1.3093 0.0474 
## 9     6.75  37.44        0.81 24 1.6607 0.0030 
## 10   10.11  41.64        0.85 24 1.8971 0.0158</code></pre>
<p>After calculating the effect size, the <code>rma()</code> function is
used for heterogeneity testing.</p>
<pre class="r"><code>#heterogeneity
het1&lt;-rma(total_es, yi, vi)
het1</code></pre>
<pre><code>## 
## Random-Effects Model (k = 53; tau^2 estimator: REML)
## 
## tau^2 (estimated amount of total heterogeneity): 0.0782 (SE = 0.0178)
## tau (square root of estimated tau^2 value):      0.2797
## I^2 (total heterogeneity / total variability):   92.31%
## H^2 (total variability / sampling variability):  13.01
## 
## Test for Heterogeneity:
## Q(df = 52) = 576.2518, p-val &lt; .0001
## 
## Model Results:
## 
## estimate      se     zval    pval   ci.lb   ci.ub      
##   1.6587  0.0415  40.0034  &lt;.0001  1.5775  1.7400  *** 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>pred1=predict(het1, transf=transf.iabt)#back-transformation to alpha
pred1</code></pre>
<pre><code>## 
##    pred  ci.lb  ci.ub  pi.lb  pi.ub 
##  0.8096 0.7935 0.8245 0.6686 0.8906</code></pre>
<p>In addition, you can calculate the effect size and heterogeneity
tests directly with <code>rma()</code> in one step, as shown below:</p>
<pre class="r"><code>het2&lt;-rma(measure=&quot;ABT&quot;, ai=alpha_total, ni=size, mi=mi, dat=data)#default REML
het2</code></pre>
<pre><code>## 
## Random-Effects Model (k = 53; tau^2 estimator: REML)
## 
## tau^2 (estimated amount of total heterogeneity): 0.0782 (SE = 0.0178)
## tau (square root of estimated tau^2 value):      0.2797
## I^2 (total heterogeneity / total variability):   92.31%
## H^2 (total variability / sampling variability):  13.01
## 
## Test for Heterogeneity:
## Q(df = 52) = 576.2518, p-val &lt; .0001
## 
## Model Results:
## 
## estimate      se     zval    pval   ci.lb   ci.ub      
##   1.6587  0.0415  40.0034  &lt;.0001  1.5775  1.7400  *** 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>pred2=predict(het2, transf=transf.iabt)##back-transformation to alpha
pred2</code></pre>
<pre><code>## 
##    pred  ci.lb  ci.ub  pi.lb  pi.ub 
##  0.8096 0.7935 0.8245 0.6686 0.8906</code></pre>
<p>The results from comparing HET1 and HET2 are the same, indicating
that either of them can be used.<br />
Furthermore, you can choose different estimation methods by setting the
<code>method</code> parameter. The Restricted Maximum Likelihood method
(REML) is generally used by default. If you want to use other estimation
methods, you can set <code>method="ML"</code> to use maximum likelihood
estimation.</p>
<pre class="r"><code>#method=ML
het3&lt;-rma(total_es, yi, vi, method=&quot;ML&quot;)
het3</code></pre>
<pre><code>## 
## Random-Effects Model (k = 53; tau^2 estimator: ML)
## 
## tau^2 (estimated amount of total heterogeneity): 0.0765 (SE = 0.0172)
## tau (square root of estimated tau^2 value):      0.2767
## I^2 (total heterogeneity / total variability):   92.16%
## H^2 (total variability / sampling variability):  12.75
## 
## Test for Heterogeneity:
## Q(df = 52) = 576.2518, p-val &lt; .0001
## 
## Model Results:
## 
## estimate      se     zval    pval   ci.lb   ci.ub      
##   1.6588  0.0411  40.3876  &lt;.0001  1.5783  1.7393  *** 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>pred3=predict(het3, transf=transf.iabt)#back-transformation to alpha
pred3</code></pre>
<pre><code>## 
##    pred  ci.lb  ci.ub  pi.lb  pi.ub 
##  0.8096 0.7937 0.8244 0.6706 0.8900</code></pre>
<p>Interpretation of the results:</p>
<ol style="list-style-type: decimal">
<li><p>The figure above shows the results of estimation using a
random-effects model, with 53 effect sizes and maximum likelihood
estimation.</p></li>
<li><p>Four indicators are provided for evaluating the heterogeneity: τ,
τ2, H2, and I2. Among them, I2 is about 92%, indicating a high level of
heterogeneity according to the criteria.</p></li>
<li><p>The Q value is 576.2518 with <em>p</em>&lt;.0001, indicating that
the heterogeneity test was significant.</p></li>
<li><p>Based on the results of the different estimation methods,
heterogeneity exists. Therefore, it is necessary to further explore the
factors contributing to the heterogeneity of these α coefficients.<br />
In addition to directly extracting the results, you can also use code to
organize the results in <em>R</em>, which is more convenient and
fast.<br />
—- this part is mainly based on R if and loop code, and does not involve
reliability generalization analysis, so it will not be further expanded
here. —-</p></li>
</ol>
<p>The following table shows the results of the heterogeneity
analysis.</p>
<pre class="r"><code>het3_res %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="right">k</th>
<th align="right">mean_alpha</th>
<th align="right">CI.LB</th>
<th align="right">CI.UB</th>
<th align="right">Tau2</th>
<th align="left">Q</th>
<th align="right">I2_precent</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">53</td>
<td align="right">0.81</td>
<td align="right">0.79</td>
<td align="right">0.82</td>
<td align="right">0.077</td>
<td align="left">576.252***</td>
<td align="right">92.16</td>
</tr>
</tbody>
</table>
</div>
<div id="forest-plot" class="section level3">
<h3>2.3 Forest plot</h3>
<p>Use the <code>forest.rma()</code> function to build a forest plot to
visualize the distribution of effect size.</p>
<pre class="r"><code>forest.rma(het3)#transformed alpha</code></pre>
<p><img src="Tutorial_Reliability-Generalization_files/figure-html/forest0-1.png" width="768" /></p>
<p>Interpretation of the results: The figure displays the name of each
study in the first column, the distribution of effect size in the
middle, and the effect size corresponding to each study and their
confidence interval on the right.<br />
You can also adjust the parameters as needed. Here are some
options:<br />
(1) Set <code>annotate=TRUE</code> to add labels to the figure. This is
generally the default setting.<br />
(2) Use <code>transf</code> to convert the effect size.<br />
(3) Use <code>showweights</code> to set the weights for presenting the
impact of each studies on the overall effect size.<br />
(4) Use <code>header</code> to determine whether to include a header in
the figure.</p>
<p>The specific code is as follows:</p>
<pre class="r"><code>forest.rma(het3,annotate=TRUE,transf=transf.iabt,header = TRUE,showweights=TRUE)#backtransformed alpha</code></pre>
<p><img src="Tutorial_Reliability-Generalization_files/figure-html/forest1-1.png" width="768" /></p>
<p>Interpretation of the results:<br />
(1) A mean effect of 0.81 was estimated using a random-effects
model.<br />
(2) The analysis yielded a mean α coefficient of 0.81, indicating good
internal consistency.<br />
To save the result graph as a pdf, use the following code:</p>
<pre class="r"><code>pdf(&quot;forestplot.pdf&quot;,width=10, height=20)
forest.rma(het3,annotate=TRUE,transf=transf.iabt,header = TRUE,showweights=TRUE)#backtransformed alpha
dev.off()</code></pre>
<pre><code>## quartz_off_screen 
##                 2</code></pre>
</div>
<div id="moderator-analysis" class="section level3">
<h3>2.4 Moderator analysis</h3>
<p>Moderator analysis is mainly done by setting the <code>mods</code>
parameter in <code>rma()</code> in order to analyze the effect of the
included moderator on heterogeneity results.<br />
The analysis parameter setting is typically used:
<code>rma (total_es, yi, vi, mods = ~ moderator)</code>.</p>
<div id="example-of-a-continuous-variable" class="section level4">
<h4>2.4.1 Example of a continuous variable</h4>
<p>Using the standard deviation of the total score of the scale as an
example, the code to include a single moderator for analysis is as
follows:</p>
<pre class="r"><code>res_tot_totalSD&lt;-rma(total_es, yi, vi, mods=~totalSD,method=&quot;ML&quot;)
res_tot_totalSD</code></pre>
<pre><code>## 
## Mixed-Effects Model (k = 53; tau^2 estimator: ML)
## 
## tau^2 (estimated amount of residual heterogeneity):     0.0521 (SE = 0.0124)
## tau (square root of estimated tau^2 value):             0.2282
## I^2 (residual heterogeneity / unaccounted variability): 88.81%
## H^2 (unaccounted variability / sampling variability):   8.94
## R^2 (amount of heterogeneity accounted for):            31.99%
## 
## Test for Residual Heterogeneity:
## QE(df = 51) = 405.6720, p-val &lt; .0001
## 
## Test of Moderators (coefficient 2):
## QM(df = 1) = 20.9010, p-val &lt; .0001
## 
## Model Results:
## 
##          estimate      se    zval    pval   ci.lb   ci.ub      
## intrcpt    0.7581  0.2003  3.7851  0.0002  0.3655  1.1506  *** 
## totalSD    0.1051  0.0230  4.5718  &lt;.0001  0.0600  0.1502  *** 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<pre class="r"><code>res_tot_totalSD&lt;-rma(measure=&quot;ABT&quot;, ai=alpha_total, ni=size, mi=mi, mods=~totalSD,dat=  data,method=&quot;ML&quot;) #same results, the difference is that the variables in the dataset are used directly
res_tot_totalSD</code></pre>
<pre><code>## 
## Mixed-Effects Model (k = 53; tau^2 estimator: ML)
## 
## tau^2 (estimated amount of residual heterogeneity):     0.0521 (SE = 0.0124)
## tau (square root of estimated tau^2 value):             0.2282
## I^2 (residual heterogeneity / unaccounted variability): 88.81%
## H^2 (unaccounted variability / sampling variability):   8.94
## R^2 (amount of heterogeneity accounted for):            31.99%
## 
## Test for Residual Heterogeneity:
## QE(df = 51) = 405.6720, p-val &lt; .0001
## 
## Test of Moderators (coefficient 2):
## QM(df = 1) = 20.9010, p-val &lt; .0001
## 
## Model Results:
## 
##          estimate      se    zval    pval   ci.lb   ci.ub      
## intrcpt    0.7581  0.2003  3.7851  0.0002  0.3655  1.1506  *** 
## totalSD    0.1051  0.0230  4.5718  &lt;.0001  0.0600  0.1502  *** 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Interpretation of the results:<br />
(1) The moderator analysis used the the maximum likelihood estimation
based on the mixed-effects model, as shown in the first row.<br />
(2) The effect of the moderators are also reported, with
<em>p</em>&lt;.0001, indicating that the standard deviation of the total
score of the scale has a moderating effect on the effect size.</p>
<p>In addition to directly extracting the results after analyzing each
variable, you can also use code in R and organize the results, which is
convenient and fast.</p>
<p>—– This section mainly involves R if and loop code and does not
involve reliability generalization analysis. Therefore, it will not be
further expanded here. —-</p>
<p>The following table shows the results of the moderator analysis of
continuous variables included.</p>
<pre class="r"><code>reg_res %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">k</th>
<th align="right">b</th>
<th align="right">t</th>
<th align="right">sig.t</th>
<th align="right">R2_percentage</th>
<th align="left">QE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">ageM</td>
<td align="right">53</td>
<td align="right">-0.010</td>
<td align="right">-1.160</td>
<td align="right">0.246</td>
<td align="right">3.57</td>
<td align="left">518.487 ***</td>
</tr>
<tr class="even">
<td align="left">ageSD</td>
<td align="right">53</td>
<td align="right">-0.018</td>
<td align="right">-0.591</td>
<td align="right">0.555</td>
<td align="right">0.66</td>
<td align="left">573.47 ***</td>
</tr>
<tr class="odd">
<td align="left">gender</td>
<td align="right">53</td>
<td align="right">0.127</td>
<td align="right">0.934</td>
<td align="right">0.350</td>
<td align="right">2.10</td>
<td align="left">563.457 ***</td>
</tr>
<tr class="even">
<td align="left">size</td>
<td align="right">53</td>
<td align="right">0.000</td>
<td align="right">-0.310</td>
<td align="right">0.757</td>
<td align="right">0.34</td>
<td align="left">563.269 ***</td>
</tr>
<tr class="odd">
<td align="left">totalSD</td>
<td align="right">53</td>
<td align="right">0.105</td>
<td align="right">4.572</td>
<td align="right">0.000</td>
<td align="right">31.99</td>
<td align="left">405.672 ***</td>
</tr>
<tr class="even">
<td align="left">totalM</td>
<td align="right">53</td>
<td align="right">0.005</td>
<td align="right">1.053</td>
<td align="right">0.292</td>
<td align="right">1.63</td>
<td align="left">576.245 ***</td>
</tr>
</tbody>
</table>
<pre class="r"><code>#b=beta
#t=significance test of moderator regression coefficient--zval
#sig.t=p-value
#R2% explain</code></pre>
</div>
<div id="examples-of-categorical-variables" class="section level4">
<h4>2.4.2 Examples of categorical variables</h4>
<p>To present an analysis of categorical variables in moderator analysis
using the example of administration ratings, the following code is shown
as follows:</p>
<div id="subgroup-analysis" class="section level6">
<h6>(1) Subgroup Analysis</h6>
<pre class="r"><code>sub_1=rma(total_es, yi, vi, subset = (total_es$ratingformat == 1))
predict(sub_1, transf=transf.iabt) #backtransformed alpha</code></pre>
<pre><code>## 
##    pred  ci.lb  ci.ub  pi.lb  pi.ub 
##  0.8047 0.7878 0.8202 0.6725 0.8835</code></pre>
<pre class="r"><code>sub_2=rma (total_es, yi, vi, subset = (total_es$ratingformat == 2))
predict(sub_2, transf=transf.iabt)#backtransformed alpha</code></pre>
<pre><code>## 
##    pred  ci.lb  ci.ub  pi.lb  pi.ub 
##  0.8203 0.7711 0.8588 0.6757 0.9004</code></pre>
<pre class="r"><code>sub_3=rma (total_es, yi, vi, subset = (total_es$ratingformat == 3))
predict(sub_3, transf=transf.iabt) #backtransformed alpha</code></pre>
<pre><code>## 
##    pred  ci.lb  ci.ub  pi.lb  pi.ub 
##  0.8717 0.7335 0.9383 0.5565 0.9629</code></pre>
<p>The table below shows the results of the subgroup analysis.</p>
<pre class="r"><code>mod_res %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">group</th>
<th align="right">k</th>
<th align="right">alpha</th>
<th align="left">ci_95</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Infants and young children</td>
<td align="right">1</td>
<td align="right">0.91</td>
<td align="left">[ 0.9 , 0.92 ]</td>
</tr>
<tr class="even">
<td align="left">Children</td>
<td align="right">9</td>
<td align="right">0.80</td>
<td align="left">[ 0.74 , 0.85 ]</td>
</tr>
<tr class="odd">
<td align="left">Adolescents</td>
<td align="right">34</td>
<td align="right">0.81</td>
<td align="left">[ 0.79 , 0.83 ]</td>
</tr>
<tr class="even">
<td align="left">Adults</td>
<td align="right">9</td>
<td align="right">0.80</td>
<td align="left">[ 0.79 , 0.81 ]</td>
</tr>
<tr class="odd">
<td align="left">community</td>
<td align="right">18</td>
<td align="right">0.82</td>
<td align="left">[ 0.79 , 0.85 ]</td>
</tr>
<tr class="even">
<td align="left">offender</td>
<td align="right">35</td>
<td align="right">0.80</td>
<td align="left">[ 0.79 , 0.82 ]</td>
</tr>
<tr class="odd">
<td align="left">english</td>
<td align="right">34</td>
<td align="right">0.81</td>
<td align="left">[ 0.79 , 0.82 ]</td>
</tr>
<tr class="even">
<td align="left">non-english</td>
<td align="right">19</td>
<td align="right">0.82</td>
<td align="left">[ 0.79 , 0.84 ]</td>
</tr>
<tr class="odd">
<td align="left">self-report</td>
<td align="right">45</td>
<td align="right">0.80</td>
<td align="left">[ 0.79 , 0.82 ]</td>
</tr>
<tr class="even">
<td align="left">parent-report</td>
<td align="right">6</td>
<td align="right">0.82</td>
<td align="left">[ 0.77 , 0.86 ]</td>
</tr>
<tr class="odd">
<td align="left">teacher-report</td>
<td align="right">2</td>
<td align="right">0.87</td>
<td align="left">[ 0.73 , 0.94 ]</td>
</tr>
</tbody>
</table>
</div>
<div id="meta-anova" class="section level5">
<h5>(2) Meta-Anova</h5>
<pre class="r"><code>res_tot_adf&lt;-rma(total_es, yi, vi,mods=~ratingformat,method=&quot;ML&quot;)
res_tot_adf</code></pre>
<pre><code>## 
## Mixed-Effects Model (k = 53; tau^2 estimator: ML)
## 
## tau^2 (estimated amount of residual heterogeneity):     0.0692 (SE = 0.0158)
## tau (square root of estimated tau^2 value):             0.2630
## I^2 (residual heterogeneity / unaccounted variability): 91.30%
## H^2 (unaccounted variability / sampling variability):   11.49
## R^2 (amount of heterogeneity accounted for):            9.64%
## 
## Test for Residual Heterogeneity:
## QE(df = 51) = 434.7357, p-val &lt; .0001
## 
## Test of Moderators (coefficient 2):
## QM(df = 1) = 4.2441, p-val = 0.0394
## 
## Model Results:
## 
##               estimate      se     zval    pval   ci.lb   ci.ub      
## intrcpt         1.4559  0.1061  13.7171  &lt;.0001  1.2479  1.6639  *** 
## ratingformat    0.1718  0.0834   2.0601  0.0394  0.0084  0.3352    * 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>The results of the effect of the moderators were
reported,<em>p</em>&lt;.05, indicating that the effect was on the
adminstration ratings.</p>
<p>The following table is the result of the moderator analysis of
categorical variables.</p>
<pre class="r"><code>anv_res %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">variable</th>
<th align="right">k</th>
<th align="right">R2_percentage</th>
<th align="right">QB</th>
<th align="right">sig</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">agetype</td>
<td align="right">53</td>
<td align="right">6.13</td>
<td align="right">2.480</td>
<td align="right">0.115</td>
</tr>
<tr class="even">
<td align="left">sampletype</td>
<td align="right">53</td>
<td align="right">2.05</td>
<td align="right">1.026</td>
<td align="right">0.311</td>
</tr>
<tr class="odd">
<td align="left">language</td>
<td align="right">53</td>
<td align="right">1.02</td>
<td align="right">0.506</td>
<td align="right">0.477</td>
</tr>
<tr class="even">
<td align="left">ratingformat</td>
<td align="right">53</td>
<td align="right">9.64</td>
<td align="right">4.244</td>
<td align="right">0.039</td>
</tr>
</tbody>
</table>
</div>
</div>
<div id="examples-of-exploratory-models" class="section level4">
<h4>2.4.3 Examples of exploratory models</h4>
<p>Select the above variables with moderating effect or high explanatory
percentage into the model for analysis, and the specific code is as
follows:</p>
<pre class="r"><code>#full model
res_multi&lt;-rma(total_es, yi, vi, mods=~ageM+totalM+totalSD+ratingformat,method=&quot;ML&quot;)
res_multi#R2=36.79%</code></pre>
<pre><code>## 
## Mixed-Effects Model (k = 53; tau^2 estimator: ML)
## 
## tau^2 (estimated amount of residual heterogeneity):     0.0484 (SE = 0.0116)
## tau (square root of estimated tau^2 value):             0.2200
## I^2 (residual heterogeneity / unaccounted variability): 87.70%
## H^2 (unaccounted variability / sampling variability):   8.13
## R^2 (amount of heterogeneity accounted for):            36.79%
## 
## Test for Residual Heterogeneity:
## QE(df = 48) = 333.9638, p-val &lt; .0001
## 
## Test of Moderators (coefficients 2:5):
## QM(df = 4) = 25.0511, p-val &lt; .0001
## 
## Model Results:
## 
##               estimate      se     zval    pval    ci.lb   ci.ub      
## intrcpt         0.6577  0.2803   2.3468  0.0189   0.1084  1.2070    * 
## ageM           -0.0024  0.0087  -0.2768  0.7819  -0.0194  0.0146      
## totalM          0.0040  0.0041   0.9920  0.3212  -0.0039  0.0120      
## totalSD         0.0944  0.0233   4.0558  &lt;.0001   0.0488  0.1400  *** 
## ratingformat    0.0996  0.0836   1.1911  0.2336  -0.0643  0.2634      
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
</div>
</div>
<div id="publication-bias" class="section level3">
<h3>2.5 Publication bias</h3>
<div id="funnel-plot" class="section level4">
<h4>2.5.1 Funnel plot</h4>
<p>Funnel plot is a common analytical technique for sensitivity
analysis, which can visually detect whether the current study is
biased.<br />
The specific code is as follows:</p>
<pre class="r"><code>funplot1=funnel(het3,atransf=transf.iabt) #funnel plot
funplot2=funnel(het3,atransf=transf.iabt,label = TRUE)#studyID tag</code></pre>
<p><img src="Tutorial_Reliability-Generalization_files/figure-html/funnel-1.png" width="768" /></p>
<p>Interpretation of the results:<br />
As can be seen from the figure, scatter points are mainly distributed at
the top of the funnel and concentrated in the middle, indicating no or
low probability of publication bias.</p>
<p>In addition, the Trim-and-fill method was used to analyze for
publication bias as follows:</p>
<pre class="r"><code>tf=trimfill(het3,estimator = &quot;R0&quot;) #Trim-and-fill 
tf</code></pre>
<pre><code>## 
## Estimated number of missing studies on the right side: 0 (SE = 1.4142)
## Test of H0: no missing studies on the right side:      p-val = 0.5000
## 
## Random-Effects Model (k = 53; tau^2 estimator: ML)
## 
## tau^2 (estimated amount of total heterogeneity): 0.0765 (SE = 0.0172)
## tau (square root of estimated tau^2 value):      0.2767
## I^2 (total heterogeneity / total variability):   92.16%
## H^2 (total variability / sampling variability):  12.75
## 
## Test for Heterogeneity:
## Q(df = 52) = 576.2518, p-val &lt; .0001
## 
## Model Results:
## 
## estimate      se     zval    pval   ci.lb   ci.ub      
##   1.6588  0.0411  40.3876  &lt;.0001  1.5783  1.7393  *** 
## 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</code></pre>
<p>Interpretation of the results:<br />
Estimates using the Trim-and-fill method found that the number of
missing studies on the right side of the estimate was 0, indicating no
bias.</p>
<p>In addition, the correlation between effect size and sampling
variance can be further analyzed. If the correlation is high, it
indicates that the funnel graph is asymmetric, that is, there is
bias.</p>
<pre class="r"><code>ranktest (total_es$yi, total_es$vi,exact=FALSE) #correlation coefficient 0.05 - Low correlation - funnel plot is symmetric - no or low risk of bias. </code></pre>
<pre><code>## 
## Rank Correlation Test for Funnel Plot Asymmetry
## 
## Kendall&#39;s tau = 0.0494, p = 0.6019</code></pre>
</div>
<div id="fail-safe-n" class="section level4">
<h4>2.5.2 Fail-safe N</h4>
<p>Use the <code>fsn()</code> function to calculate the Fail-safe N with
the following code:</p>
<pre class="r"><code>fail_safe=fsn(yi, vi, data=total_es,type=&quot;Rosenthal&quot;)
fail_safe</code></pre>
<pre><code>## 
## Fail-safe N Calculation Using the Rosenthal Approach
## 
## Observed Significance Level: &lt;.0001
## Target Significance Level:   0.05
## 
## Fail-safe N: 359983</code></pre>
<pre class="r"><code>5*nrow(data)+10# was compared to the calculated results of 5*k+10 (k is the number of included analyses).</code></pre>
<pre><code>## [1] 275</code></pre>
<p>Interpretation of the results: (1) Line 1 indicates that the
Fail-safe N was calculated using the “Rosenthal” method.<br />
(2) The Fail-safe N is compared to the calculated result of 5*k + 10
(where k is the number of included analyses). If the Fail-safe N is less
than the calculated value, then there is a risk of publication
bias.<br />
(3) The results show the Fail-safe N of 359983, which is much higher
than the number included in the analysis, indicating no publication
bias.</p>
<p>In general, Fail-safe N are generally collated with heterogeneity
results, as follows:</p>
<pre class="r"><code>het3_res %&gt;% knitr::kable()</code></pre>
<table>
<colgroup>
<col width="4%" />
<col width="17%" />
<col width="9%" />
<col width="9%" />
<col width="9%" />
<col width="17%" />
<col width="17%" />
<col width="15%" />
</colgroup>
<thead>
<tr class="header">
<th align="right">k</th>
<th align="right">mean_alpha</th>
<th align="right">CI.LB</th>
<th align="right">CI.UB</th>
<th align="right">Tau2</th>
<th align="left">Q</th>
<th align="right">I2_precent</th>
<th align="left">FSN</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">53</td>
<td align="right">0.81</td>
<td align="right">0.79</td>
<td align="right">0.82</td>
<td align="right">0.077</td>
<td align="left">576.252***</td>
<td align="right">92.16</td>
<td align="left">359983***</td>
</tr>
</tbody>
</table>
</div>
<div id="calculate-the-eggers-regression-test" class="section level4">
<h4>2.5.3 Calculate the Egger’s regression test</h4>
<p>Use the <code>regtest()</code> function for the Egger’s regression
test as follows:</p>
<pre class="r"><code>regtest(het3, model=&quot;lm&quot;)### classical Egger test</code></pre>
<pre><code>## 
## Regression Test for Funnel Plot Asymmetry
## 
## Model:     weighted regression with multiplicative dispersion
## Predictor: standard error
## 
## Test for Funnel Plot Asymmetry: t = 0.5984, df = 51, p = 0.5522
## Limit Estimate (as sei -&gt; 0):   b = 1.6015 (CI: 1.4359, 1.7672)</code></pre>
<p>Interpretation of the results: From the results, the Egger regression
coefficient intercept was not significant, indicating that there was no
bias or the possibility of bias was low.</p>
</div>
<div id="summary" class="section level4">
<h4>2.5.4 Summary</h4>
<p>In summary, the results of multiple analyses, including funnel plot,
Trim-and-fill method, Rosenthal Fail-safe N, and Egger’s regression
test, indicate a low risk of bias or the absence of publication bias in
this study.</p>
<pre class="r"><code>bias %&gt;% knitr::kable()</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">method</th>
<th align="left">results</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">funnelplot</td>
<td align="left">symmetrical</td>
</tr>
<tr class="even">
<td align="left">fsn</td>
<td align="left">Fail-safe N: 359983 &gt; 5*53+10=275</td>
</tr>
<tr class="odd">
<td align="left">egger</td>
<td align="left">t = 0.5984, df = 51, p = 0.5522</td>
</tr>
</tbody>
</table>
</div>
<div id="export-the-results" class="section level4">
<h4>2.6 Export the results</h4>
<p>After all the analysis is completed, use the <code>write()</code>
function to export the results for use in a paper or analysis
report.</p>
<pre class="r"><code>#write.xlsx (het3_res, file = &quot;heterogeneity test results.xlsx&quot;)
#write.xlsx (reg_res, file = &quot;continuous moderator results.xlsx&quot;)
#write.xlsx (anv_res, file = &quot;categorical moderator results.xlsx&quot;)</code></pre>
</div>
</div>
<div id="practice" class="section level3">
<h3>Practice</h3>
<p>Try using the built-in data <code>dat.bonett2010</code> to complete a
full analysis process. The code for importing the data is provided
below:</p>
<pre class="r"><code>dat &lt;- dat.bonett2010
#description: Results from 9 studies on the reliability of the Center for Epidemiologic Studies Depression (CES-D) Scale administered to children providing care to an elderly parent.</code></pre>
</div>
</div>
<div id="summary-1" class="section level2">
<h2>3. Summary</h2>
<p>First, the statistical analysis process of reliability generalization
is described using<code>metafor</code>with examples, including effect
size calculation, heterogeneity testing, moderation analysis, and
publication bias.</p>
<div class="figure">
<img
src="https://www.metafor-project.org/lib/exe/fetch.php/docs:diagram.png"
alt="" />
<p class="caption">Overview of the functions of metafor (from the
official website of metafor-project)</p>
</div>
<p>Secondly, the analytical strategy can be adjusted according to the
purpose and aims of the research.</p>
<blockquote>
<p>Take-away messages</p>
</blockquote>
<ol style="list-style-type: decimal">
<li>As a meta-analysis technique that uses the reliability coefficient
as the effect size, reliability generalization has both the common and
specificity of meta-analysis.
<ul>
<li>Find out if there is a “Reliability Induction” issue.</li>
<li>Comprehensively evaluate whether a tool is stable and reliable.</li>
</ul></li>
<li><code>metafor</code>provides more options for the implementation of
statistical analysis of reliabilit generalization.
<ul>
<li>Choose the appropriate analysis method according to the aim.</li>
</ul></li>
</ol>
<hr />
</div>
<div id="resources" class="section level2">
<h2>4. Resources</h2>
<div id="cran-documentation" class="section level3">
<h3>4.1 CRAN documentation</h3>
<p>Since the developer will update the R package, the code need to be
used based on the manual if any updates.</p>
<pre class="r"><code>help(metafor) #manual
? metaphor</code></pre>
<pre><code>## No documentation for &#39;metaphor&#39; in specified packages and libraries:
## you could try &#39;??metaphor&#39;</code></pre>
<pre class="r"><code>? escalc()
#escalc# Take escalc() as an example to look at the source code to understand the underlying logic</code></pre>
</div>
<div id="metaforofficial-website" class="section level3">
<h3>4.2 <code>metafor</code>official website</h3>
<p>Here are two useful websites that provide a lot of resources.<br />
<a
href="https://wviechtb.github.io/metafor/index.html">metafor@github</a><br />
[Metafor-Project website] (<a
href="https://www.metafor-project.org/doku.php"
class="uri">https://www.metafor-project.org/doku.php</a>).</p>
</div>
<div id="reference-books" class="section level3">
<h3>4.3 Reference books</h3>
<p>Harrer, M., Cuijpers, P., Furukawa, T. A., &amp; Ebert, D. D. (2021).
<em>Doing meta-analysis with R: A hands-on guide</em>. Chapman and
Hall/CRC.</p>
<p>Polanin, J. R., Hennessy, E. A., &amp; Tanner-Smith, E. E. (2017). A
Review of Meta-Analysis Packages in R. <em>Journal of Educational and
Behavioral Statistics</em>, <em>42</em>, 206–242.</p>
<p>Viechtbauer, W. (2010). Conducting meta-analyses in R with the
metafor package. <em>Journal of Statistical Software</em>, <em>36</em>,
1–48.</p>
</div>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
